In [1]:
my_list = [1,2,3,4]

In [12]:
my_list

[1, 2, 3, 4]

In [11]:
import numpy as np
arr= np.array(my_list)

In [13]:
arr

array([1, 2, 3, 4])

To create a 2d array 

In [7]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr2d=np.array(mat)

In [14]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To create a array within a range of no.s

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

To create array of zeroes

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

To create array of ones

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

To create an array with evenly spaced points b/w two no.s

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

To create a identity matrix useful when dealing with linear algebra

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

to create an array of random no.s

In [26]:
np.random.rand(5)

array([0.89584891, 0.05605859, 0.22457301, 0.88310908, 0.70051683])

In [27]:
np.random.rand(3,3)

array([[0.64261487, 0.91372403, 0.25307216],
       [0.06175397, 0.24968828, 0.331782  ],
       [0.83388931, 0.16410984, 0.31239918]])

To return a random no.s from standard normal distribution

In [30]:
np.random.randn(5)

array([ 0.21146775,  1.38778194, -0.62218841,  0.14580788, -0.73572825])

To return randomintegersarray in low high range

In [29]:
np.random.randint(1,100,5)

array([17, 16, 96, 62, 79])

In [31]:
arr2=np.arange(30)

In [32]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
arr2.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [37]:
arr2.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
arr2.min()

0

In [39]:
arr2.max()

29

In [40]:
arr2.argmax()

29

In [41]:
ranarr=np.random.randint(0,50,10)

In [42]:
ranarr

array([43, 40, 34,  4, 43, 26, 26, 33, 40, 34])

In [43]:
ranarr.max()

43

In [44]:
ranarr.argmax()

0

In [45]:
ranarr.min()

4

In [46]:
ranarr.argmin()

3

In [48]:
ranarr.shape

(10,)

In [49]:
ranarr.reshape(2,5)

array([[43, 40, 34,  4, 43],
       [26, 26, 33, 40, 34]])

In [51]:
ranarr.dtype

dtype('int32')

In [52]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])