# PYTHON

# series

In [1]:
import numpy as np 
import pandas as pd

In [2]:
char = ['a','b','c']
num_list=[1,2,3]
arr= np.array(num_list)
dict={'a':1,'b':2,'c':3}

In [3]:
arr

array([1, 2, 3])

In [4]:
dict

{'a': 1, 'b': 2, 'c': 3}

In [5]:
pd.Series(data=arr)

0    1
1    2
2    3
dtype: int32

In [6]:
pd.Series(arr,char)

a    1
b    2
c    3
dtype: int32

In [7]:
pd.Series(dict)

a    1
b    2
c    3
dtype: int64

In [8]:
ser1 = pd.Series([1,2,3,4],['Usa','India','Japan','Korea'])

In [9]:
ser1

Usa      1
India    2
Japan    3
Korea    4
dtype: int64

In [10]:
ser2 = pd.Series([1,2,5,4],['Usa','India','China','Korea'])

In [11]:
ser2

Usa      1
India    2
China    5
Korea    4
dtype: int64

In [12]:
ser1+ser2

China    NaN
India    4.0
Japan    NaN
Korea    8.0
Usa      2.0
dtype: float64

In [13]:
ser3=pd.Series({'Usa':1,'India':2,'Japan':3})

In [14]:
ser3

Usa      1
India    2
Japan    3
dtype: int64

# Dataframe 

In [15]:
from numpy.random import randn
np.random.seed(1)

In [16]:
df= pd.DataFrame(randn(3,3),['A','B','C'],['X','Y','Z'])

In [17]:
df

X         Y         Z
A  1.624345 -0.611756 -0.528172
B -1.072969  0.865408 -2.301539
C  1.744812 -0.761207  0.319039

In [18]:
df['X']

A    1.624345
B   -1.072969
C    1.744812
Name: X, dtype: float64

In [19]:
type(df['X'])

pandas.core.series.Series

In [20]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df['new']=df['X']+df['Y']

In [22]:
df

X         Y         Z       new
A  1.624345 -0.611756 -0.528172  1.012589
B -1.072969  0.865408 -2.301539 -0.207561
C  1.744812 -0.761207  0.319039  0.983605

In [23]:
df.drop('new',axis=1,inplace=True)

In [24]:
df

X         Y         Z
A  1.624345 -0.611756 -0.528172
B -1.072969  0.865408 -2.301539
C  1.744812 -0.761207  0.319039

Two ways to grab a row

In [25]:
df.loc['A']

X    1.624345
Y   -0.611756
Z   -0.528172
Name: A, dtype: float64

2nd way is index location

In [26]:
df.iloc[2]

X    1.744812
Y   -0.761207
Z    0.319039
Name: C, dtype: float64

In [27]:
df.loc[:,'X':'Y']

X         Y
A  1.624345 -0.611756
B -1.072969  0.865408
C  1.744812 -0.761207

In [28]:
df.loc[:'B',:'Y']

X         Y
A  1.624345 -0.611756
B -1.072969  0.865408

In [29]:
df.iloc[-1]

X    1.744812
Y   -0.761207
Z    0.319039
Name: C, dtype: float64

In [30]:
df[df['Z']>0]

X         Y         Z
C  1.744812 -0.761207  0.319039

In [31]:
resultdf=df[df['Z']>0]

In [32]:
resultdf['X']

C    1.744812
Name: X, dtype: float64

instead of doing all the above 3 steps we can do that in 1 step

In [33]:
df[df['Z']>0]['X']

C    1.744812
Name: X, dtype: float64

In [34]:
df[df['Z']>0][['X','Y']]

X         Y
C  1.744812 -0.761207

resetting index

In [35]:
df.reset_index()

index         X         Y         Z
0     A  1.624345 -0.611756 -0.528172
1     B -1.072969  0.865408 -2.301539
2     C  1.744812 -0.761207  0.319039

In [36]:
newindex='a b c'.split()

In [37]:
df['new']=newindex

In [38]:
df

X         Y         Z new
A  1.624345 -0.611756 -0.528172   a
B -1.072969  0.865408 -2.301539   b
C  1.744812 -0.761207  0.319039   c

To set index to a column

In [39]:
df.set_index('new')

X         Y         Z
new                              
a    1.624345 -0.611756 -0.528172
b   -1.072969  0.865408 -2.301539
c    1.744812 -0.761207  0.319039

In [43]:
df['X'].value_counts()

-1.072969    1
 1.744812    1
 1.624345    1
Name: X, dtype: int64

In [46]:
df.values

array([[1.6243453636632417, -0.6117564136500754, -0.5281717522634557,
        'a'],
       [-1.0729686221561705, 0.8654076293246785, -2.3015386968802827,
        'b'],
       [1.74481176421648, -0.7612069008951028, 0.31903909605709857, 'c']],
      dtype=object)

In [47]:
df['X'].uniqueque()

array([ 1.62434536, -1.07296862,  1.74481176])

In [51]:
df.isnull().sum()

X      0
Y      0
Z      0
new    0
dtype: int64

In [54]:
df1=pd.read_csv('train.csv')

In [55]:
df1

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [56]:
df1=pd.read_csv('train.csv',usecols=['Id','LotFrontage'])

In [57]:
df1

Id  LotFrontage
0        1         65.0
1        2         80.0
2        3         68.0
3        4         60.0
4        5         84.0
...    ...          ...
1455  1456         62.0
1456  1457         85.0
1457  1458         66.0
1458  1459         68.0
1459  1460         75.0

[1460 rows x 2 columns]

In [62]:
df1=pd.read_csv('train.csv',index_col=2)

In [64]:
df1

Id  MSSubClass  LotFrontage  LotArea Street Alley LotShape  \
MSZoning                                                                 
RL           1          60         65.0     8450   Pave   NaN      Reg   
RL           2          20         80.0     9600   Pave   NaN      Reg   
RL           3          60         68.0    11250   Pave   NaN      IR1   
RL           4          70         60.0     9550   Pave   NaN      IR1   
RL           5          60         84.0    14260   Pave   NaN      IR1   
...        ...         ...          ...      ...    ...   ...      ...   
RL        1456          60         62.0     7917   Pave   NaN      Reg   
RL        1457          20         85.0    13175   Pave   NaN      Reg   
RL        1458          70         66.0     9042   Pave   NaN      Reg   
RL        1459          20         68.0     9717   Pave   NaN      Reg   
RL        1460          20         75.0     9937   Pave   NaN      Reg   

         LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence  \
MSZoning                                  ...                          
RL               Lvl    AllPub    Inside  ...        0    NaN    NaN   
RL               Lvl    AllPub       FR2  ...        0    NaN    NaN   
RL               Lvl    AllPub    Inside  ...        0    NaN    NaN   
RL               Lvl    AllPub    Corner  ...        0    NaN    NaN   
RL               Lvl    AllPub       FR2  ...        0    NaN    NaN   
...              ...       ...       ...  ...      ...    ...    ...   
RL               Lvl    AllPub    Inside  ...        0    NaN    NaN   
RL               Lvl    AllPub    Inside  ...        0    NaN  MnPrv   
RL               Lvl    AllPub    Inside  ...        0    NaN  GdPrv   
RL               Lvl    AllPub    Inside  ...        0    NaN    NaN   
RL               Lvl    AllPub    Inside  ...        0    NaN    NaN   

         MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  \
MSZoning                                                               
RL               NaN       0      2    2008        WD         Normal   
RL               NaN       0      5    2007        WD         Normal   
RL               NaN       0      9    2008        WD         Normal   
RL               NaN       0      2    2006        WD        Abnorml   
RL               NaN       0     12    2008        WD         Normal   
...              ...     ...    ...     ...       ...            ...   
RL               NaN       0      8    2007        WD         Normal   
RL               NaN       0      2    2010        WD         Normal   
RL              Shed    2500      5    2010        WD         Normal   
RL               NaN       0      4    2010        WD         Normal   
RL               NaN       0      6    2008        WD         Normal   

          SalePrice  
MSZoning             
RL           208500  
RL           181500  
RL           223500  
RL           140000  
RL           250000  
...             ...  
RL           175000  
RL           210000  
RL           266500  
RL           142125  
RL           147500  

[1460 rows x 80 columns]

# For converting data into csv

In [65]:
df1.to_csv('new.csv')

# Pandas - Groupby

In [86]:
d={'comp':['google','google','apple','fb','apple','fb'],'name':['sam','charlie','jason','smith','kenny','simp'],'sales':[200,np.nan,150,450,np.nan,250]}

In [87]:
df2=pd.DataFrame(d)

In [88]:
df2

comp     name  sales
0  google      sam  200.0
1  google  charlie    NaN
2   apple    jason  150.0
3      fb    smith  450.0
4   apple    kenny    NaN
5      fb     simp  250.0

In [89]:
df2.groupby('comp').sum()

sales
comp         
apple   150.0
fb      700.0
google  200.0

In [103]:
df2.groupby('comp').count().loc['fb']

name     2
sales    2
Name: fb, dtype: int64

In [ ]:
To apply groupy and find NAN sales value on basis of another feature and fill it with mean value

In [100]:
df2['sales']=df2.groupby(['comp'])['sales'].apply(lambda col :col.fillna(col.mean()))

In [101]:
df2['sales']

0    200.0
1    200.0
2    150.0
3    450.0
4    150.0
5    250.0
Name: sales, dtype: float64

In [102]:
df2

comp     name  sales
0  google      sam  200.0
1  google  charlie  200.0
2   apple    jason  150.0
3      fb    smith  450.0
4   apple    kenny  150.0
5      fb     simp  250.0